spring:
  datasource:
    password: wohaya
    username: memoire
    url: jdbc:postgresql://localhost:5432/wohaya

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
